services:
  usuarios:
    build: 
      context: ./proyecto24-gb01-usuarios
    ports:
      - "8081:8081"
    networks:
      - medifli
    environment:
      - CONTENIDOS_URL=http://contenidos:8082/
      - ESTADISTICAS_URL=http://estadisticas:8083/
      - INTERFAZ_URL=http://interfaz:8080/
      - SPRING_DATASOURCE_URL=jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - h2-data:/root/.h2  # Volumen para persistir los datos de H2 en disco

  contenidos:
    build: 
      context: ./proyecto24-gb01-contenidos
    ports:
      - "8082:8082"
    environment:
      - USUARIOS_URL=http://usuarios:8081/
      - ESTADISTICAS_URL=http://estadisticas:8083/
      - INTERFAZ_URL=http://interfaz:8080/
      - MONGO_HOST=mongodb-contenidos
      - MONGO_PORT=27017
    networks:
      - medifli
    depends_on:
      - mongodb-contenidos

  estadisticas:
    build: 
      context: ./proyecto24-gb01-estadisticas
    ports:
      - "8083:8083"
    environment:
      - USUARIOS_URL=http://usuarios:8081/
      - CONTENIDOS_URL=http://contenidos:8082/
      - INTERFAZ_URL=http://interfaz:8080/
      - MONGO_HOST=mongodb-estadisticas
      - MONGO_PORT=27018
    networks:
      - medifli
    depends_on:
      - mongodb-estadisticas

  interfaz:
    build: 
      context: ./interfaz
    ports:
      - "8080:8080"
    environment:
      - USUARIOS_URL=http://usuarios:8081/
      - CONTENIDOS_URL=http://contenidos:8082/
      - ESTADISTICAS_URL=http://estadisticas:8083/
    networks:
      - medifli
    depends_on:
      - usuarios
      - contenidos
      - estadisticas

  mongodb-contenidos:
    image: mongo:latest
    container_name: mongodb-contenidos
    environment:
      - MONGO_INITDB_DATABASE=MedifliContent
    ports:
      - "27017:27017"
    networks:
      - medifli
    volumes:
      - mongodb-contenidos-data:/data/db

  mongodb-estadisticas:
    image: mongo:latest
    container_name: mongodb-estadisticas
    command: ["mongod", "--port", "27018"]  # Cambia el puerto interno a 28018

    environment:
      - MONGO_INITDB_DATABASE=MedifliStats
    ports:
      - "27018:27018"
    networks:
      - medifli
    volumes:
      - mongodb-estadisticas-data:/data/db

networks:
  medifli:
    driver: bridge

volumes:
  mongodb-contenidos-data:
  mongodb-estadisticas-data:
  h2-data:
    driver: local
