name: Learning actions (DEV)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'dev'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
          
      - name: Build and start services with Docker Compose
        run: |
          docker compose up -d
